words = {
    wIntensifier: [
        'super',
        'very',
        'hella',
        'totally'
    ],

    nClimb: [
        'crimpfest',
        'slopefest',
        'pumpfest',
        'chosspile',
        'testpiece',
        'rig',
        'bloc',
        'highball',
        'line',
        'rock climb'
    ],

    nFeature: [
        'scoop',
        'seam',
        'hueco',
        'crack',
        'cave',
        'roof',
        'pit',
        
    ],
    
    nClimbFeature: [
        'prow',
        'arete',
        'face',
        'slab',
        'bulge',
        'dihedral',
        'chimney',
        'seam',
        'ramp',
        'feature',
    ],
    
    vClimbFeature: [
        'quest',
        'ascend',
        'climb',
        'move'
    ],
    
    climberAdj: [
        'short',
        'tall',
        'young',
        'old',
        'weak',
        'strong',
    ],
    
    nGrade: [
        'V1',
        'V2',
        'V3',
        'V4',
        'V5',
        'V6',
        'V7',
        'V8',
        'V9',
        'V10',
        'V11',
        'V12',
        'V13',
        'V14',
        'V15',
        'V16',
        '5.4',
        '5.5',
        '5.6',
        '5.7',
        '5.8',
        '5.9',
        '5.10',
        '5.11',
        '5.12',
        '5.13',
        '5.14',
        '5.15'
    ],

    nHold: [
        'sloper',
        'jug',
        'crimp',
        'rail',
        'undercling',
        'edge',
        'pinch',
        'pocket',
        'mono',
        'slot',
        'flake',
        'cobble',
        'horn',
        'dish',
    ],

    nHolds: [
        'cobbles',
        'slopers',
        'jugs',
        'crimps',
        'rails',
        'underclings',
        'edges',
        'pinches',
        'pockets',
        'monos',
        'slots',
        'flakes',
        'dishes',
    ],

    nMove: [
        'move',
        'deadpoint',
        'dyno',
        'cross',
        'high-step',
        'lock-off',
        'reach',
        'drop-knee',
        'mantel',
        'invert',
        'foot jam',
        'figure four',
        'drive-by',
        'windmill',
        'gaston',
        'heel hook',
        'toe hook',
        'heel-toe cam',
        'hand jam',
        'ring lock',
        'chicken wing',
        'double clutch',
    ],

    vStart: [
        'establish',
        'start',
        'begin'
    ],
    
    vFinish:[
        'end',
        'finish'
    ],

    vDo: [
        'make',
        'pull',
        'do',
        'hit',
        'pull off'
    ],
    
    vMaintain: [
        'stay sharp',
        'look alive',
        'get nutty',
        'get buck',
        'pull the stops',
        'pump the brakes',
        'stoke the fire',
        'keep cool',
        'keep calm',
        'keep your wits about you',
        'don\'t panic',
        'keep it together',
        'hold on',
        'bite down',
        'fire the jets',
        'ignite the core',
        'pop the cork',
        'stay tight',
        'stomp the gas',
        'mash',
    ],

    vMove: [
        'move',
        'traverse',
        'thrutch',
        'huck',
        'burl',
        'throw',
        'pull',
        'surf out',
        'slap',
        'bear down',
        'campus',
        'float',
        'glide',
        'cruise',
        'grovel',
    ],

    vHold: [
        'grab',
        'crimp',
        'squeeze',
        'pinch',
        'control',
        'dominate',
        'slap',
        'lock down',
        'endure',
        'hit',
        'mash'
    ],

    climbAdj: [
        'thought-provoking',
        'interesting',
        'fun',
        'flowy',
        'techy',
        'technical',
        'mega',
        'chossy',
        'insecure',
        'morpho',
        'burly',
        'height-dependent',
        'sandbagged',
        'long',
        'short',
        'cruxy',
        'sustained',
        'death',
        'gym-y',
        'beta-intensive',
        'spicy',
        'stylistic',
        'imposing',
        'steep',
        'slabby',
        'gonzo',
        'iconic',
        'proud',
        'humble',
        'garbage',
        'humble',
        'futuristic',
        'aesthetic',
        'beautiful',
        'gorgeous',
        'new-age',
    ],

    moveAdj: [
        'delicate',
        'strong',
        'insecure',
        'long',
        'short',
        'burly',
        'technical',
        'spicy',
        'core-intensive',
        'reachy',
        'powerful',
        'strenuous',
        'flashy',
        'desperate',
        'hefty',
        'slick',
        'bonebending',
        'risky',
        'snappy',
        'wide',
        'steezy',
        'next-gen',
    ],

    holdAdj: [
        'slopey',
        'pinchey',
        'crimpy',
        'heinous',
        'terrible',
        'barely-there',
        'credit-card',
        'sharp',
        'iron',
        'glassy',
        'slick',
        'sticky',
        'wide',
        'deep',
        'shallow',
        'narrow',
        'thick',
        'thin',
        'wavy',
        'juggy',
        'bomber',
        'sinker',
        'huge',
        'giant',
        'frightful',
        'full-pad',
        'half-pad',
        'quarter-pad',
        'two-finger',
        'three-finger',
        'enormous',
        'hellish',
        'sweet',
        'great',
        'beautiful',
        'gorgeous',
        'prime',
        'garbage',
        'fragile',
        'tweaky',
        '\"oh shit\"',
        '\"thank God\"',
        '\"hell no\"',
        'half-moon',
    ],
    
    wPos: [
        'high',
        'low',
        'crouched',
        'standing',
        'sitting',
        'inverted'
    ]
}
