words = {
  wIntensifier: [
    'super',
    'very',
    'extremely',
    'highly',
    'totally',
    'most',
    'exceptionally',
    'incredibly',
    'distinctively',
    'aggressively',
    'unreasonably'
  ],

  nClimb: [
    'crimpfest',
    'slopefest',
    'pumpfest',
    'chosspile',
    'testpiece',
    'rig',
    'bloc',
    'highball',
    'line',
    'rock climb',
    'climb',
    'boulder',
    'problem',
  ],

  nFeature: [
    'scoop',
    'seam',
    'hueco',
    'crack',
    'cave',
    'roof',
    'pit',
    'streak',
  ],

  nClimbFeature: [
    'prow',
    'arete',
    'face',
    'slab',
    'bulge',
    'dihedral',
    'chimney',
    'seam',
    'ramp',
    'feature',
    'corner',
    'overhang',
    'roof',
    'vert section',
  ],

  vClimbFeature: [
    'quest',
    'ascend',
    'climb',
    'move',
    'venture',
    'go',
  ],

  nHold: [
    'sloper',
    'jug',
    'crimp',
    'rail',
    'undercling',
    'edge',
    'pinch',
    'pocket',
    'mono',
    'slot',
    'flake',
    'cobble',
    'horn',
    'dish',
    'handle',
    'bulb',
    'orb',
    'disk',
    'incut',
    'block',
    'divot',
    'blob',
    'crystal',
  ],

  nHolds: [
    'cobbles',
    'slopers',
    'jugs',
    'crimps',
    'rails',
    'underclings',
    'edges',
    'pinches',
    'pockets',
    'monos',
    'slots',
    'flakes',
    'dishes',
    'handles',
    'bulbs',
    'orbs',
    'disks',
    'incuts',
    'blocks',
    'divots',
    'blobs',
    'crystals',
  ],

  nMove: [
    'move',
    'deadpoint',
    'dyno',
    'cross',
    'high-step',
    'lock-off',
    'reach',
    'drop-knee',
    'mantel',
    'invert',
    'foot jam',
    'figure four',
    'drive-by',
    'windmill',
    'gaston',
    'heel hook',
    'toe hook',
    'heel-toe cam',
    'hand jam',
    'ring lock',
    'chicken wing',
    'double clutch',
    'throw',
    'lurch',
    'match',
    'bump',
    'span',
  ],

  vStart: [
    'establish',
    'start',
    'begin'
  ],

  vFinish:[
    'end',
    'finish'
  ],

  vDo: [
    'make',
    'pull',
    'do',
    'hit',
    'pull off',
    
    
    'execute',
  ],

  vMaintain: [
    'stay sharp',
    'look alive',
    'get nutty',
    'get buck',
    'pull the stops',
    'pump the brakes',
    'stoke the fire',
    'keep cool',
    'keep calm',
    'keep your wits about you',
    'don\'t panic',
    'keep it together',
    'hold on',
    'bite down',
    'fire the jets',
    'ignite the core',
    'pop the cork',
    'stay tight',
    'stomp the gas',
    'mash',
    'go ape',
    'blow up',
    'aggro',
  ],

  vMove: [
    'move',
    'traverse',
    'thrutch',
    'huck',
    'burl',
    'throw',
    'pull',
    'surf out',
    'slap',
    'bear down',
    'campus',
    'float',
    'glide',
    'cruise',
    'grovel',
    'tiptoe',
    'slide',
    'skate',
    'grind',
  ],

  vHold: [
    'grab',
    'crimp',
    'squeeze',
    'pinch',
    'control',
    'dominate',
    'slap',
    'lock down',
    'endure',
    'hit',
    'mash'
  ],

  climbAdj: [
    'thought-provoking',
    'interesting',
    'fun',
    'flowy',
    'techy',
    'technical',
    'mega',
    'chossy',
    'insecure',
    'morpho',
    'burly',
    'height-dependent',
    'sandbagged',
    'long',
    'short',
    'cruxy',
    'sustained',
    'death',
    'gym-y',
    'beta-intensive',
    'spicy',
    'stylistic',
    'imposing',
    'steep',
    'slabby',
    'gonzo',
    'iconic',
    'proud',
    'humble',
    'garbage',
    'futuristic',
    'aesthetic',
    'beautiful',
    'gorgeous',
    'new-age',
    'wacky',
    'worthwhile',
    'cruiser',
    'gnar',
    'honorable',
    'punchy',
    'classic',
    'menacing',
    'intimidating',
    'old-school',
    'new-school',
    'indelible',
    'underrated',
  ],

  moveAdj: [
    'delicate',
    'strong',
    'insecure',
    'long',
    'short',
    'burly',
    'technical',
    'spicy',
    'core-intensive',
    'reachy',
    'powerful',
    'strenuous',
    'flashy',
    'desperate',
    'hefty',
    'slick',
    'bonebending',
    'risky',
    'snappy',
    'wide',
    'steezy',
    'next-gen',
    'extreme',
    'power',
    'tenuous',
    'slow',
    'unintuitive',
    'easy',
    'blind',
    'improbable',
    'quick',
    'subtle',
    'aggressive',
    'intense',
    'ridiculous',
    'graceful',
    'gorilla',
    'wicked',
    'brutal',
    'fantastic',
    'finicky',
    'heinous',
    'super hein',
    'tough',
  ],

  holdAdj: [
    'slopey',
    'pinchey',
    'crimpy',
    'heinous',
    'terrible',
    'barely-there',
    'credit-card',
    'sharp',
    'iron',
    'glassy',
    'slick',
    'sticky',
    'wide',
    'deep',
    'shallow',
    'narrow',
    'thick',
    'thin',
    'wavy',
    'juggy',
    'bomber',
    'sinker',
    'huge',
    'giant',
    'frightful',
    'full-pad',
    'half-pad',
    'quarter-pad',
    'two-finger',
    'three-finger',
    'mono',
    'enormous',
    'hellish',
    'sweet',
    'great',
    'beautiful',
    'gorgeous',
    'prime',
    'garbage',
    'fragile',
    'tweaky',
    '\"oh shit\"',
    '\"thank God\"',
    '\"hell no\"',
    'half-moon',
    'razor',
    'blunt',
    'irregular',
    'shapely',
    'fiddly',
    'sculpted',
    'subtle',
    'rough',
    'mean',
    'finicky',
    'deep',
    'cavernous',
    'beefy',
    'bulbous',
    'dappled',
  ],

  wPos: [
    'high',
    'low',
    'crouched',
    'standing',
    'sitting',
    'inverted',
    'horizontal',
  ],

  climbName: [
    "Slick Oiler's Revenge",
    'Mungis World',
    'Kill Butt 2',
    "Huffy's Revenge",
    'Hinagon',
    'Trihelior',
    'Wine-bringer',
    '6 Gazillion',
    'Mothra vs. Kong',
    'Ninja Ninja',
    'Tornado Johnson',
    'Most Biggest Egg Ever',
    'Yung Humpernickel',
    'Bee Wash 2.0',
    'Big Computer',
    'Unlaundered',
    'Linen Flinger',
    'Good Zumba',
    'Hoit to Toit',
    'Flim',
    'Spaghetti Punch',
    'Blackbeard',
    'Yung Wimbledorf',
    'Mizzenmast',
    'Twig Lovers Anonymous',
    'Stolen Cheese',
    'Shoplifting',
    'Godzilla Sighting',
    'Basket-weaver',
    'Yellow Power Ranger',
    'Hull Breach',
    "McDonald's Problem",
    'Robo-Hedgehog',
    'Must Eat It',
    'Leor',
    'Leor Arete',
    'Leor Arete Eliminate Sit',
    'Lizard Problem',
    'Boing Boing Boing',
    'Cave Explorer',
    'Biggest Sword',
    'Mata Nui',
    'M. Bison',
    'Legatron',
    'Flour Shortage',
    'Hematomir',
    'Zizzibyr',
    'Cirrus, Stratus',
    'Set Theory',
    'Roger the Parrot',
    'Amby',
    'Dexter',
    'Timber Goose',
    'Big Duct Tape',
    'Diode',
    'Immodium',
    'L-Lysine',
    'Steroid Mart',
    'Touche, Mr. Mime',
    'Eeyore Fleece',
    'Yung Dunwithies',
    'Yung Oldman',
    "Baby's Problem",
    'Hoarders',
    'Creamstretcher',
    'Yumbono',
    'Greenhorn',
    'Dog of War',
    'Hyperion',
    'Yung Hieronymous',
    'Slizor',
    'Yung Magikarp',
    'Pomeg Berry Glitch',
    'Abtainin Mew N Deoksys',
    'Mothra vs. Gyarados',
    'Foghorn Egghorn',
    'Egghorn Leghorn',
    'Yung Trepanation',
  ],
}
